title: panoplei
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8082438
  brandStrength: 0.5
  rhythmicContrast: 0.4354839
  brandColors:
    - '#283A41'
    - '#FCFCFB'
    - '#A36E65'
    - '#429A88'
    - '#88E0D0'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: panoplei
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8888889
layout_spectrum: 1
