name: panoplei
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76448
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: panoplei
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#283A41'
    - '#FCFCFB'
    - '#A36E65'
    - '#429A88'
    - '#88E0D0'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
